location: France Central
resourceGroup: rg-aca-az-cli
type: Microsoft.App/containerApps
workloadProfileName: Consumption
properties:
  configuration:
    activeRevisionsMode: Single
    ingress:
      allowInsecure: false
      exposedPort: 0
      external: true
      targetPort: 80
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: 100
  managedEnvironmentId: /subscriptions/ab7b7ae7-e46c-4663-ad31-d93710428185/resourceGroups/rg-aca-az-cli/providers/Microsoft.App/managedEnvironments/env-aca
  patchingMode: Automatic
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - image: mcr.microsoft.com/k8se/quickstart:latest
      imageType: ContainerImage
      name: aca-quickstart
      resources:
        cpu: 0.75
        ephemeralStorage: 4Gi
        memory: 1.5Gi
    revisionSuffix: ''
    scale:
      maxReplicas: 3
      minReplicas: 1
      rules: null
  workloadProfileName: Consumption